### ISSUE TITLE
jpylyzer in third party CI

### ISSUE THREAD

**Issue by boxerab** [openpreserve/jpylyzer#163]
Hello and Congratulations on the big 2.0 release !

I would like to add the 2.0 release to the  travis CI script for grok j2k codec, but it seems there is no longer a github archive for the release.  Here is what used to work for me in travis :

```
    JPYLYZER_VERSION="1.17.0"    
	echo "Retrieving jpylyzer"
	if [ "${APPVEYOR:-}" == "True" ]; then
		wget -q http://dl.bintray.com/openplanets/opf-windows/jpylyzer_${JPYLYZER_VERSION}_win32.zip
		mkdir jpylyzer
		cd jpylyzer
		cmake -E tar -xzf ../jpylyzer_${JPYLYZER_VERSION}_win32.zip
		cd ..
	else
		wget -qO - https://github.com/openpreserve/jpylyzer/archive/${JPYLYZER_VERSION}.tar.gz | tar -xz
		mv jpylyzer-${JPYLYZER_VERSION}/jpylyzer ./
		chmod +x jpylyzer/jpylyzer.py
	fi
````

Any advice would be much appreciated.
Aaron

**Comment by bitsgalore** [comment]
Hi Aaron,

I don't quite understand the problem, since the Github archive for the 2.0 release is available from this link:

<https://github.com/openpreserve/jpylyzer/archive/2.0.0.tar.gz>

Which follows the exact pattern you're using!

On a side note, I see you're trying to get Windows binaries from Bintray, but we stopped using Bintray for that some 4 years ago already! Instead you can get those from Github as well, using links like below (for the 2.0 release):

- <https://github.com/openpreserve/jpylyzer/releases/download/2.0.0/jpylyzer_2.0.0_win64.zip> (64 bit)
- <https://github.com/openpreserve/jpylyzer/releases/download/2.0.0/jpylyzer_2.0.0_win32.zip> (32 bit)

Does this help?

**Comment by boxerab** [comment]
Thanks! You are correct, the archive tarball is there. 
For windows binaries,  you've explained the mystery of why my Appveyor builds are missing unit tests :) no jpylyzer. 

Looking forward to adding raw code stream verification now that this feature is available.

Cheers,
Aaron
