### ISSUE TITLE
Feature Request: validate RSIZ profile: cinema and IMF

### ISSUE THREAD

**Issue by boxerab** [openpreserve/jpylyzer#173]

**Comment by bitsgalore** [comment]
Validation against specific profiles within JP2 is already possible by post-processing jpylyzer's output with Schematron rules. See this old blog post I once wrote about this (note that the Schematron examples provided there are slightly outdated because of some changes to jpylyzer's output format in version 2.0):

[Automated assessment of JP2 against a technical profile](https://www.bitsgalore.org/2012/09/04/automated-assessment-jp2-against-technical-profile)

Based on a quick glance at the IMF profile specs that I found [here](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-T.800-201410-S!Amd7!PDF-E&type=items), you could simply define the profiles you're interested in as a set of Schematron rules.
