### ISSUE TITLE
Garbled sot info

### ISSUE THREAD

**Issue by boxerab** [openpreserve/jpylyzer#187]
Offending image:

[jpylyzer_bad_sot.zip](https://github.com/openpreserve/jpylyzer/files/8984739/jpylyzer_bad_sot.zip)

snippet from jpylyzer output :

```
       <tileParts>
            <tilePart>
                <sot>
                    <lsot>-9999</lsot>
                    <isot>-9999</isot>
                    <psot>-9999</psot>
                    <tpsot>-9999</tpsot>
                    <tnsot>-9999</tnsot>
                </sot>
            </tilePart>
        </tileParts>
```

**Comment by bitsgalore** [comment]
This doesn't look like a bug to me: the image is truncated immediately after the start of the SOT marker segment, which is why no meaningful values of lsot, isot, and so on can be read. This causes an exception in struct.unpack, which is [handled by the bytestr conversion function](https://github.com/openpreserve/jpylyzer/blob/94c11a5ef7033346dce0e4b06c0d4b5549438995/jpylyzer/byteconv.py#L22), resulting in the "-9999" fallback values.

The validation output also provides several clues that something is seriously wrong with the image:

```xml
<tests>
    <siz>
        <rsizIsValid>False</rsizIsValid>
    </siz>
    <tileParts>
        <tilePart>
            <sot>
                <lsotIsValid>False</lsotIsValid>
                <isotIsValid>False</isotIsValid>
                <tpsotIsValid>False</tpsotIsValid>
            </sot>
            <foundSODMarker>False</foundSODMarker>
            <foundNextTilePartOrEOC>False</foundNextTilePartOrEOC>
        </tilePart>
    </tileParts>
    <foundEOCMarker>False</foundEOCMarker>
</tests>
```

**Comment by boxerab** [comment]
Yes, you're right. For some reason I though the SOT marker was intact. Closing.
