### ISSUE TITLE
Hard-coded path in test_test.py (PY27 support and Travis questions)

### ISSUE THREAD

**Issue by ross-spencer** [openpreserve/jpylyzer#189]
I was looking at the Python 2.7 issues following the 2.1 announcement. These are stopping Travis from passing. 

Some issues are easier than others, e.g. the encoding string missing in `test_testfiles.py`:

```diff
diff --git a/tests/unit/test_testfiles.py b/tests/unit/test_testfiles.py
index 1414027..e130227 100644
--- a/tests/unit/test_testfiles.py
+++ b/tests/unit/test_testfiles.py
@@ -1,4 +1,5 @@
 #! /usr/bin/env python3
+# -*- coding:utf-8 -*-
 # pylint: disable=missing-docstring
 """
 Tests on jpylyzer test corpus files.
```

Others are a bit trickier. I tried looking at `test_test.py`, but we have a couple of different issues: 

https://github.com/openpreserve/jpylyzer/blob/92d3eaa409733988e09700d79be3803f58028794/tests/unit/test_test.py#L44

Requires `path.walk()` or perhaps import of `pathlib2` for `pathlib.iterdir()` would work well for `py2` and `py3`. 

But we have this hard-coded path too: https://github.com/openpreserve/jpylyzer/blob/92d3eaa409733988e09700d79be3803f58028794/tests/unit/test_test.py#L41

From the module docstring: https://github.com/openpreserve/jpylyzer/blob/92d3eaa409733988e09700d79be3803f58028794/tests/unit/test_test.py#L8

 it seems this maybe should be corrected to `../jpylyzer-test-files` but it's not clear and different test errors start to appear once this is corrected. 

> NB. It seems to work because `pytest.parametize()` likely receives an empty array `[]` which satisfies the requirement to be iterable. It means nothing runs on my environment (test is skipped) but it will work on Johan's.
>
> In one draft of my updates I've suggested a check to make sure it is there before we arrive in the test (this just makes sense when trying not to refactor too much):`assert os.path.isdir(testFilesDir), "jpylyzer test files directory not found: {}".replace(testFilesDir)`

It's not clear the intent of `test_xml_onefile()`. It looks like an integration test and it catches anything that may fall out of the code that may be unknown, i.e. unhandled exceptions from odd files. Which makes sense. 

My questions though are two fold: 

1. Does the test file `test_test.py` warrant inclusion in the code-base still? What needs to be done for it to be run by maintainers? Do we have access to all the test files required in `jpylyzer-test-files` 
2. Does Python 2.7 compatibility make sense still, should it just be removed from travis from now? If it does make sense, what steps need to be taken to bring it up to 2.7 before it is removed in 2.2?

Connected to https://github.com/openpreserve/jpylyzer/issues/179

**Comment by bitsgalore** [comment]
Thanks reporting this @ross-spencer! As for the `test_test.py` file: I should have deleted that earlier, it was just something I created locally to figure out how to implement the tests that ended up in `test_testfiles.py`. Done now!

Your comments also made me realise that Travis CI is still working, but that the web domain of the server has changed. I just updated that as well in the readme file, but now Travis fails with (e.g. [here](https://app.travis-ci.com/github/openpreserve/jpylyzer/jobs/579074222 ):

```
The command "if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then pylint --disable R0201,R0902,R0904,R0912,R0913,R0914,R0915,R1702,R1703 --disable W0511,W0702,W0703 --disable C0200,C0302  setup.py ./tests/ ./jpylyzer/; fi" failed and exited with 28 during .

Your build has been stopped.
```
Initially though this was caused by several `R0801: Similar lines in n files` Pylint errors that were triggered from the unit tests, but after disabling that error the build still fails. Perhaps @carlwilson could have a look at this?

About the Python 2.7 support and Travis: good question . For now I just added the UTF-8 encoding declarations, but with the end of Python 2.7 support for Jpylyzer nearly in sight I don't think it's worth it to put much additional effort into this.

**Comment by bitsgalore** [comment]
I created a separate issue for the failing Travis build <https://github.com/openpreserve/jpylyzer/issues/190>

**Comment by bitsgalore** [comment]
Py 3.5 Travis build works now!

**Comment by ross-spencer** [comment]
Nice work Johan, and thanks for the feedback also. All makes sense. I would also take the same approach with 2.7. Largely I was just wondering what the intention between the 2.1 release and 2.2 release may be with regard to fixing anything. All makes sense! :slightly_smiling_face:
