### ISSUE TITLE
Project still active ?

### ISSUE THREAD

**Issue by boxerab** [openpreserve/jpylyzer#97]
Hopefully :) But, almost a year without updates ......

**Comment by bitsgalore** [comment]
Hi Aaron,

Yes, it's still very much active, but I haven't been able to give it much attention lately because I've been swamped with other things (still am). The valgrind / pychecker issues you submitted last year are on top of my list for the next iteration (in fact Stefan Weil already did some work on that and submitted this patch: <https://github.com/openpreserve/jpylyzer/pull/92> but I simply haven't had time to have proper look at it. 

I will have a look at all this (also the Debian packaging is in need of an overhaul and I'd like to add support for pip installation as well).

**Comment by boxerab** [comment]
Thanks, Johan.  This is such a great project. 

Happy New Year,
Aaron
